// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrustWalletCore.proto

package com.wallet.crypto.trustapp.jni;

public final class TrustWalletCore {
  private TrustWalletCore() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface OutPointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TrustWalletCore.OutPoint)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional bytes hash = 1;</code>
     */
    com.google.protobuf.ByteString getHash();

    /**
     * <code>optional uint32 index = 2;</code>
     */
    int getIndex();
  }
  /**
   * Protobuf type {@code TrustWalletCore.OutPoint}
   */
  public  static final class OutPoint extends
      com.google.protobuf.GeneratedMessageLite<
          OutPoint, OutPoint.Builder> implements
      // @@protoc_insertion_point(message_implements:TrustWalletCore.OutPoint)
      OutPointOrBuilder {
    private OutPoint() {
      hash_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int HASH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString hash_;
    /**
     * <code>optional bytes hash = 1;</code>
     */
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }
    /**
     * <code>optional bytes hash = 1;</code>
     */
    private void setHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hash_ = value;
    }
    /**
     * <code>optional bytes hash = 1;</code>
     */
    private void clearHash() {
      
      hash_ = getDefaultInstance().getHash();
    }

    public static final int INDEX_FIELD_NUMBER = 2;
    private int index_;
    /**
     * <code>optional uint32 index = 2;</code>
     */
    public int getIndex() {
      return index_;
    }
    /**
     * <code>optional uint32 index = 2;</code>
     */
    private void setIndex(int value) {
      
      index_ = value;
    }
    /**
     * <code>optional uint32 index = 2;</code>
     */
    private void clearIndex() {
      
      index_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!hash_.isEmpty()) {
        output.writeBytes(1, hash_);
      }
      if (index_ != 0) {
        output.writeUInt32(2, index_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!hash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, hash_);
      }
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, index_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code TrustWalletCore.OutPoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint, Builder> implements
        // @@protoc_insertion_point(builder_implements:TrustWalletCore.OutPoint)
        com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPointOrBuilder {
      // Construct using com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional bytes hash = 1;</code>
       */
      public com.google.protobuf.ByteString getHash() {
        return instance.getHash();
      }
      /**
       * <code>optional bytes hash = 1;</code>
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setHash(value);
        return this;
      }
      /**
       * <code>optional bytes hash = 1;</code>
       */
      public Builder clearHash() {
        copyOnWrite();
        instance.clearHash();
        return this;
      }

      /**
       * <code>optional uint32 index = 2;</code>
       */
      public int getIndex() {
        return instance.getIndex();
      }
      /**
       * <code>optional uint32 index = 2;</code>
       */
      public Builder setIndex(int value) {
        copyOnWrite();
        instance.setIndex(value);
        return this;
      }
      /**
       * <code>optional uint32 index = 2;</code>
       */
      public Builder clearIndex() {
        copyOnWrite();
        instance.clearIndex();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TrustWalletCore.OutPoint)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint other = (com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint) arg1;
          hash_ = visitor.visitByteString(hash_ != com.google.protobuf.ByteString.EMPTY, hash_,
              other.hash_ != com.google.protobuf.ByteString.EMPTY, other.hash_);
          index_ = visitor.visitInt(index_ != 0, index_,
              other.index_ != 0, other.index_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {

                  hash_ = input.readBytes();
                  break;
                }
                case 16: {

                  index_ = input.readUInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TrustWalletCore.OutPoint)
    private static final com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OutPoint();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<OutPoint> PARSER;

    public static com.google.protobuf.Parser<OutPoint> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UnspentTransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TrustWalletCore.UnspentTransaction)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
     */
    boolean hasOutPoint();
    /**
     * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
     */
    com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint getOutPoint();

    /**
     * <code>optional bytes script = 2;</code>
     */
    com.google.protobuf.ByteString getScript();

    /**
     * <code>optional int64 amount = 3;</code>
     */
    long getAmount();
  }
  /**
   * Protobuf type {@code TrustWalletCore.UnspentTransaction}
   */
  public  static final class UnspentTransaction extends
      com.google.protobuf.GeneratedMessageLite<
          UnspentTransaction, UnspentTransaction.Builder> implements
      // @@protoc_insertion_point(message_implements:TrustWalletCore.UnspentTransaction)
      UnspentTransactionOrBuilder {
    private UnspentTransaction() {
      script_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int OUT_POINT_FIELD_NUMBER = 1;
    private com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint outPoint_;
    /**
     * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
     */
    public boolean hasOutPoint() {
      return outPoint_ != null;
    }
    /**
     * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
     */
    public com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint getOutPoint() {
      return outPoint_ == null ? com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint.getDefaultInstance() : outPoint_;
    }
    /**
     * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
     */
    private void setOutPoint(com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint value) {
      if (value == null) {
        throw new NullPointerException();
      }
      outPoint_ = value;
      
      }
    /**
     * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
     */
    private void setOutPoint(
        com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint.Builder builderForValue) {
      outPoint_ = builderForValue.build();
      
    }
    /**
     * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
     */
    private void mergeOutPoint(com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint value) {
      if (outPoint_ != null &&
          outPoint_ != com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint.getDefaultInstance()) {
        outPoint_ =
          com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint.newBuilder(outPoint_).mergeFrom(value).buildPartial();
      } else {
        outPoint_ = value;
      }
      
    }
    /**
     * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
     */
    private void clearOutPoint() {  outPoint_ = null;
      
    }

    public static final int SCRIPT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString script_;
    /**
     * <code>optional bytes script = 2;</code>
     */
    public com.google.protobuf.ByteString getScript() {
      return script_;
    }
    /**
     * <code>optional bytes script = 2;</code>
     */
    private void setScript(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      script_ = value;
    }
    /**
     * <code>optional bytes script = 2;</code>
     */
    private void clearScript() {
      
      script_ = getDefaultInstance().getScript();
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private long amount_;
    /**
     * <code>optional int64 amount = 3;</code>
     */
    public long getAmount() {
      return amount_;
    }
    /**
     * <code>optional int64 amount = 3;</code>
     */
    private void setAmount(long value) {
      
      amount_ = value;
    }
    /**
     * <code>optional int64 amount = 3;</code>
     */
    private void clearAmount() {
      
      amount_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (outPoint_ != null) {
        output.writeMessage(1, getOutPoint());
      }
      if (!script_.isEmpty()) {
        output.writeBytes(2, script_);
      }
      if (amount_ != 0L) {
        output.writeInt64(3, amount_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (outPoint_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getOutPoint());
      }
      if (!script_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, script_);
      }
      if (amount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, amount_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code TrustWalletCore.UnspentTransaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction, Builder> implements
        // @@protoc_insertion_point(builder_implements:TrustWalletCore.UnspentTransaction)
        com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransactionOrBuilder {
      // Construct using com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
       */
      public boolean hasOutPoint() {
        return instance.hasOutPoint();
      }
      /**
       * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
       */
      public com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint getOutPoint() {
        return instance.getOutPoint();
      }
      /**
       * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
       */
      public Builder setOutPoint(com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint value) {
        copyOnWrite();
        instance.setOutPoint(value);
        return this;
        }
      /**
       * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
       */
      public Builder setOutPoint(
          com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint.Builder builderForValue) {
        copyOnWrite();
        instance.setOutPoint(builderForValue);
        return this;
      }
      /**
       * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
       */
      public Builder mergeOutPoint(com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint value) {
        copyOnWrite();
        instance.mergeOutPoint(value);
        return this;
      }
      /**
       * <code>optional .TrustWalletCore.OutPoint out_point = 1;</code>
       */
      public Builder clearOutPoint() {  copyOnWrite();
        instance.clearOutPoint();
        return this;
      }

      /**
       * <code>optional bytes script = 2;</code>
       */
      public com.google.protobuf.ByteString getScript() {
        return instance.getScript();
      }
      /**
       * <code>optional bytes script = 2;</code>
       */
      public Builder setScript(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setScript(value);
        return this;
      }
      /**
       * <code>optional bytes script = 2;</code>
       */
      public Builder clearScript() {
        copyOnWrite();
        instance.clearScript();
        return this;
      }

      /**
       * <code>optional int64 amount = 3;</code>
       */
      public long getAmount() {
        return instance.getAmount();
      }
      /**
       * <code>optional int64 amount = 3;</code>
       */
      public Builder setAmount(long value) {
        copyOnWrite();
        instance.setAmount(value);
        return this;
      }
      /**
       * <code>optional int64 amount = 3;</code>
       */
      public Builder clearAmount() {
        copyOnWrite();
        instance.clearAmount();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TrustWalletCore.UnspentTransaction)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction other = (com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction) arg1;
          outPoint_ = visitor.visitMessage(outPoint_, other.outPoint_);
          script_ = visitor.visitByteString(script_ != com.google.protobuf.ByteString.EMPTY, script_,
              other.script_ != com.google.protobuf.ByteString.EMPTY, other.script_);
          amount_ = visitor.visitLong(amount_ != 0L, amount_,
              other.amount_ != 0L, other.amount_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint.Builder subBuilder = null;
                  if (outPoint_ != null) {
                    subBuilder = outPoint_.toBuilder();
                  }
                  outPoint_ = input.readMessage(com.wallet.crypto.trustapp.jni.TrustWalletCore.OutPoint.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(outPoint_);
                    outPoint_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 18: {

                  script_ = input.readBytes();
                  break;
                }
                case 24: {

                  amount_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TrustWalletCore.UnspentTransaction)
    private static final com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UnspentTransaction();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UnspentTransaction> PARSER;

    public static com.google.protobuf.Parser<UnspentTransaction> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SigningProviderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TrustWalletCore.SigningProvider)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated bytes private_keys = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getPrivateKeysList();
    /**
     * <code>repeated bytes private_keys = 1;</code>
     */
    int getPrivateKeysCount();
    /**
     * <code>repeated bytes private_keys = 1;</code>
     */
    com.google.protobuf.ByteString getPrivateKeys(int index);

    /**
     * <code>map&lt;string, bytes&gt; scripts = 2;</code>
     */
    int getScriptsCount();
    /**
     * <code>map&lt;string, bytes&gt; scripts = 2;</code>
     */
    boolean containsScripts(
        java.lang.String key);
    /**
     * Use {@link #getScriptsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getScripts();
    /**
     * <code>map&lt;string, bytes&gt; scripts = 2;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getScriptsMap();
    /**
     * <code>map&lt;string, bytes&gt; scripts = 2;</code>
     */

    com.google.protobuf.ByteString getScriptsOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue);
    /**
     * <code>map&lt;string, bytes&gt; scripts = 2;</code>
     */

    com.google.protobuf.ByteString getScriptsOrThrow(
        java.lang.String key);

    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    java.util.List<com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction> 
        getUtxosList();
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction getUtxos(int index);
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    int getUtxosCount();
  }
  /**
   * Protobuf type {@code TrustWalletCore.SigningProvider}
   */
  public  static final class SigningProvider extends
      com.google.protobuf.GeneratedMessageLite<
          SigningProvider, SigningProvider.Builder> implements
      // @@protoc_insertion_point(message_implements:TrustWalletCore.SigningProvider)
      SigningProviderOrBuilder {
    private SigningProvider() {
      privateKeys_ = emptyProtobufList();
      utxos_ = emptyProtobufList();
    }
    public static final int PRIVATE_KEYS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> privateKeys_;
    /**
     * <code>repeated bytes private_keys = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getPrivateKeysList() {
      return privateKeys_;
    }
    /**
     * <code>repeated bytes private_keys = 1;</code>
     */
    public int getPrivateKeysCount() {
      return privateKeys_.size();
    }
    /**
     * <code>repeated bytes private_keys = 1;</code>
     */
    public com.google.protobuf.ByteString getPrivateKeys(int index) {
      return privateKeys_.get(index);
    }
    private void ensurePrivateKeysIsMutable() {
      if (!privateKeys_.isModifiable()) {
        privateKeys_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(privateKeys_);
       }
    }
    /**
     * <code>repeated bytes private_keys = 1;</code>
     */
    private void setPrivateKeys(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePrivateKeysIsMutable();
      privateKeys_.set(index, value);
    }
    /**
     * <code>repeated bytes private_keys = 1;</code>
     */
    private void addPrivateKeys(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePrivateKeysIsMutable();
      privateKeys_.add(value);
    }
    /**
     * <code>repeated bytes private_keys = 1;</code>
     */
    private void addAllPrivateKeys(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensurePrivateKeysIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, privateKeys_);
    }
    /**
     * <code>repeated bytes private_keys = 1;</code>
     */
    private void clearPrivateKeys() {
      privateKeys_ = emptyProtobufList();
    }

    public static final int SCRIPTS_FIELD_NUMBER = 2;
    private static final class ScriptsDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, com.google.protobuf.ByteString> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.BYTES,
                  com.google.protobuf.ByteString.EMPTY);
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, com.google.protobuf.ByteString> scripts_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, com.google.protobuf.ByteString>
    internalGetScripts() {
      return scripts_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, com.google.protobuf.ByteString>
    internalGetMutableScripts() {
      if (!scripts_.isMutable()) {
        scripts_ = scripts_.mutableCopy();
      }
      return scripts_;
    }

    public int getScriptsCount() {
      return internalGetScripts().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; scripts = 2;</code>
     */

    public boolean containsScripts(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetScripts().containsKey(key);
    }
    /**
     * Use {@link #getScriptsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getScripts() {
      return getScriptsMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; scripts = 2;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getScriptsMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetScripts());
    }
    /**
     * <code>map&lt;string, bytes&gt; scripts = 2;</code>
     */

    public com.google.protobuf.ByteString getScriptsOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetScripts();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; scripts = 2;</code>
     */

    public com.google.protobuf.ByteString getScriptsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetScripts();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, bytes&gt; scripts = 2;</code>
     */
    private java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getMutableScriptsMap() {
      return internalGetMutableScripts();
    }

    public static final int UTXOS_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction> utxos_;
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    public java.util.List<com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction> getUtxosList() {
      return utxos_;
    }
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    public java.util.List<? extends com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransactionOrBuilder> 
        getUtxosOrBuilderList() {
      return utxos_;
    }
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    public int getUtxosCount() {
      return utxos_.size();
    }
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    public com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction getUtxos(int index) {
      return utxos_.get(index);
    }
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    public com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransactionOrBuilder getUtxosOrBuilder(
        int index) {
      return utxos_.get(index);
    }
    private void ensureUtxosIsMutable() {
      if (!utxos_.isModifiable()) {
        utxos_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(utxos_);
       }
    }

    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    private void setUtxos(
        int index, com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureUtxosIsMutable();
      utxos_.set(index, value);
    }
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    private void setUtxos(
        int index, com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction.Builder builderForValue) {
      ensureUtxosIsMutable();
      utxos_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    private void addUtxos(com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureUtxosIsMutable();
      utxos_.add(value);
    }
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    private void addUtxos(
        int index, com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureUtxosIsMutable();
      utxos_.add(index, value);
    }
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    private void addUtxos(
        com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction.Builder builderForValue) {
      ensureUtxosIsMutable();
      utxos_.add(builderForValue.build());
    }
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    private void addUtxos(
        int index, com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction.Builder builderForValue) {
      ensureUtxosIsMutable();
      utxos_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    private void addAllUtxos(
        java.lang.Iterable<? extends com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction> values) {
      ensureUtxosIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, utxos_);
    }
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    private void clearUtxos() {
      utxos_ = emptyProtobufList();
    }
    /**
     * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
     */
    private void removeUtxos(int index) {
      ensureUtxosIsMutable();
      utxos_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < privateKeys_.size(); i++) {
        output.writeBytes(1, privateKeys_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
           : internalGetScripts().entrySet()) {
        ScriptsDefaultEntryHolder.defaultEntry.serializeTo(
            output, 2, entry.getKey(), entry.getValue());
      }
      for (int i = 0; i < utxos_.size(); i++) {
        output.writeMessage(3, utxos_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < privateKeys_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(privateKeys_.get(i));
        }
        size += dataSize;
        size += 1 * getPrivateKeysList().size();
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
           : internalGetScripts().entrySet()) {
        size += ScriptsDefaultEntryHolder.defaultEntry.computeMessageSize(
          2, entry.getKey(), entry.getValue());
      }
      for (int i = 0; i < utxos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, utxos_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code TrustWalletCore.SigningProvider}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider, Builder> implements
        // @@protoc_insertion_point(builder_implements:TrustWalletCore.SigningProvider)
        com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProviderOrBuilder {
      // Construct using com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated bytes private_keys = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getPrivateKeysList() {
        return java.util.Collections.unmodifiableList(
            instance.getPrivateKeysList());
      }
      /**
       * <code>repeated bytes private_keys = 1;</code>
       */
      public int getPrivateKeysCount() {
        return instance.getPrivateKeysCount();
      }
      /**
       * <code>repeated bytes private_keys = 1;</code>
       */
      public com.google.protobuf.ByteString getPrivateKeys(int index) {
        return instance.getPrivateKeys(index);
      }
      /**
       * <code>repeated bytes private_keys = 1;</code>
       */
      public Builder setPrivateKeys(
          int index, com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPrivateKeys(index, value);
        return this;
      }
      /**
       * <code>repeated bytes private_keys = 1;</code>
       */
      public Builder addPrivateKeys(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addPrivateKeys(value);
        return this;
      }
      /**
       * <code>repeated bytes private_keys = 1;</code>
       */
      public Builder addAllPrivateKeys(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        copyOnWrite();
        instance.addAllPrivateKeys(values);
        return this;
      }
      /**
       * <code>repeated bytes private_keys = 1;</code>
       */
      public Builder clearPrivateKeys() {
        copyOnWrite();
        instance.clearPrivateKeys();
        return this;
      }


      public int getScriptsCount() {
        return instance.getScriptsMap().size();
      }
      /**
       * <code>map&lt;string, bytes&gt; scripts = 2;</code>
       */

      public boolean containsScripts(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return instance.getScriptsMap().containsKey(key);
      }

      public Builder clearScripts() {
        copyOnWrite();
        instance.getMutableScriptsMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, bytes&gt; scripts = 2;</code>
       */

      public Builder removeScripts(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        copyOnWrite();
        instance.getMutableScriptsMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getScriptsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getScripts() {
        return getScriptsMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; scripts = 2;</code>
       */
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getScriptsMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getScriptsMap());
      }
      /**
       * <code>map&lt;string, bytes&gt; scripts = 2;</code>
       */

      public com.google.protobuf.ByteString getScriptsOrDefault(
          java.lang.String key,
          com.google.protobuf.ByteString defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
            instance.getScriptsMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, bytes&gt; scripts = 2;</code>
       */

      public com.google.protobuf.ByteString getScriptsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
            instance.getScriptsMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, bytes&gt; scripts = 2;</code>
       */
      public Builder putScripts(
          java.lang.String key,
          com.google.protobuf.ByteString value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        copyOnWrite();
        instance.getMutableScriptsMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, bytes&gt; scripts = 2;</code>
       */
      public Builder putAllScripts(
          java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
        copyOnWrite();
        instance.getMutableScriptsMap().putAll(values);
        return this;
      }

      /**
       * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
       */
      public java.util.List<com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction> getUtxosList() {
        return java.util.Collections.unmodifiableList(
            instance.getUtxosList());
      }
      /**
       * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
       */
      public int getUtxosCount() {
        return instance.getUtxosCount();
      }/**
       * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
       */
      public com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction getUtxos(int index) {
        return instance.getUtxos(index);
      }
      /**
       * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
       */
      public Builder setUtxos(
          int index, com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction value) {
        copyOnWrite();
        instance.setUtxos(index, value);
        return this;
      }
      /**
       * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
       */
      public Builder setUtxos(
          int index, com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction.Builder builderForValue) {
        copyOnWrite();
        instance.setUtxos(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
       */
      public Builder addUtxos(com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction value) {
        copyOnWrite();
        instance.addUtxos(value);
        return this;
      }
      /**
       * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
       */
      public Builder addUtxos(
          int index, com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction value) {
        copyOnWrite();
        instance.addUtxos(index, value);
        return this;
      }
      /**
       * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
       */
      public Builder addUtxos(
          com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction.Builder builderForValue) {
        copyOnWrite();
        instance.addUtxos(builderForValue);
        return this;
      }
      /**
       * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
       */
      public Builder addUtxos(
          int index, com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction.Builder builderForValue) {
        copyOnWrite();
        instance.addUtxos(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
       */
      public Builder addAllUtxos(
          java.lang.Iterable<? extends com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction> values) {
        copyOnWrite();
        instance.addAllUtxos(values);
        return this;
      }
      /**
       * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
       */
      public Builder clearUtxos() {
        copyOnWrite();
        instance.clearUtxos();
        return this;
      }
      /**
       * <code>repeated .TrustWalletCore.UnspentTransaction utxos = 3;</code>
       */
      public Builder removeUtxos(int index) {
        copyOnWrite();
        instance.removeUtxos(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TrustWalletCore.SigningProvider)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          privateKeys_.makeImmutable();
          scripts_.makeImmutable();
          utxos_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider other = (com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider) arg1;
          privateKeys_= visitor.visitList(privateKeys_, other.privateKeys_);
          scripts_ = visitor.visitMap(
              scripts_, other.internalGetScripts());
          utxos_= visitor.visitList(utxos_, other.utxos_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!privateKeys_.isModifiable()) {
                    privateKeys_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(privateKeys_);
                  }
                  privateKeys_.add(input.readBytes());
                  break;
                }
                case 18: {
                  if (!scripts_.isMutable()) {
                    scripts_ = scripts_.mutableCopy();
                  }
                  ScriptsDefaultEntryHolder.defaultEntry.parseInto(scripts_, input, extensionRegistry);  break;
                }
                case 26: {
                  if (!utxos_.isModifiable()) {
                    utxos_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(utxos_);
                  }
                  utxos_.add(
                      input.readMessage(com.wallet.crypto.trustapp.jni.TrustWalletCore.UnspentTransaction.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TrustWalletCore.SigningProvider)
    private static final com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SigningProvider();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.wallet.crypto.trustapp.jni.TrustWalletCore.SigningProvider getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SigningProvider> PARSER;

    public static com.google.protobuf.Parser<SigningProvider> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
