/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.TW.proto.BitcoinSigningOutput');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.TW.proto.BitcoinTransaction');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TW.proto.BitcoinSigningOutput = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.TW.proto.BitcoinSigningOutput, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.TW.proto.BitcoinSigningOutput.displayName = 'proto.TW.proto.BitcoinSigningOutput';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TW.proto.BitcoinSigningOutput.prototype.toObject = function(opt_includeInstance) {
  return proto.TW.proto.BitcoinSigningOutput.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TW.proto.BitcoinSigningOutput} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TW.proto.BitcoinSigningOutput.toObject = function(includeInstance, msg) {
  var f, obj = {
    transaction: (f = msg.getTransaction()) && proto.TW.proto.BitcoinTransaction.toObject(includeInstance, f),
    encoded: msg.getEncoded_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TW.proto.BitcoinSigningOutput}
 */
proto.TW.proto.BitcoinSigningOutput.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TW.proto.BitcoinSigningOutput;
  return proto.TW.proto.BitcoinSigningOutput.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TW.proto.BitcoinSigningOutput} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TW.proto.BitcoinSigningOutput}
 */
proto.TW.proto.BitcoinSigningOutput.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.TW.proto.BitcoinTransaction;
      reader.readMessage(value,proto.TW.proto.BitcoinTransaction.deserializeBinaryFromReader);
      msg.setTransaction(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEncoded(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TW.proto.BitcoinSigningOutput.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TW.proto.BitcoinSigningOutput.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TW.proto.BitcoinSigningOutput} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TW.proto.BitcoinSigningOutput.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransaction();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.TW.proto.BitcoinTransaction.serializeBinaryToWriter
    );
  }
  f = message.getEncoded_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional BitcoinTransaction transaction = 1;
 * @return {?proto.TW.proto.BitcoinTransaction}
 */
proto.TW.proto.BitcoinSigningOutput.prototype.getTransaction = function() {
  return /** @type{?proto.TW.proto.BitcoinTransaction} */ (
    jspb.Message.getWrapperField(this, proto.TW.proto.BitcoinTransaction, 1));
};


/** @param {?proto.TW.proto.BitcoinTransaction|undefined} value */
proto.TW.proto.BitcoinSigningOutput.prototype.setTransaction = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.TW.proto.BitcoinSigningOutput.prototype.clearTransaction = function() {
  this.setTransaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.TW.proto.BitcoinSigningOutput.prototype.hasTransaction = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes encoded = 2;
 * @return {string}
 */
proto.TW.proto.BitcoinSigningOutput.prototype.getEncoded = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes encoded = 2;
 * This is a type-conversion wrapper around `getEncoded()`
 * @return {string}
 */
proto.TW.proto.BitcoinSigningOutput.prototype.getEncoded_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEncoded()));
};


/**
 * optional bytes encoded = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEncoded()`
 * @return {!Uint8Array}
 */
proto.TW.proto.BitcoinSigningOutput.prototype.getEncoded_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEncoded()));
};


/** @param {!(string|Uint8Array)} value */
proto.TW.proto.BitcoinSigningOutput.prototype.setEncoded = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


