/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.TW.proto.BitcoinTransaction');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.TW.proto.BitcoinTransactionInput');
goog.require('proto.TW.proto.BitcoinTransactionOutput');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TW.proto.BitcoinTransaction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.TW.proto.BitcoinTransaction.repeatedFields_, null);
};
goog.inherits(proto.TW.proto.BitcoinTransaction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.TW.proto.BitcoinTransaction.displayName = 'proto.TW.proto.BitcoinTransaction';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.TW.proto.BitcoinTransaction.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TW.proto.BitcoinTransaction.prototype.toObject = function(opt_includeInstance) {
  return proto.TW.proto.BitcoinTransaction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TW.proto.BitcoinTransaction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TW.proto.BitcoinTransaction.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, 0),
    locktime: jspb.Message.getFieldWithDefault(msg, 2, 0),
    inputsList: jspb.Message.toObjectList(msg.getInputsList(),
    proto.TW.proto.BitcoinTransactionInput.toObject, includeInstance),
    outputsList: jspb.Message.toObjectList(msg.getOutputsList(),
    proto.TW.proto.BitcoinTransactionOutput.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TW.proto.BitcoinTransaction}
 */
proto.TW.proto.BitcoinTransaction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TW.proto.BitcoinTransaction;
  return proto.TW.proto.BitcoinTransaction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TW.proto.BitcoinTransaction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TW.proto.BitcoinTransaction}
 */
proto.TW.proto.BitcoinTransaction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setVersion(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLocktime(value);
      break;
    case 3:
      var value = new proto.TW.proto.BitcoinTransactionInput;
      reader.readMessage(value,proto.TW.proto.BitcoinTransactionInput.deserializeBinaryFromReader);
      msg.addInputs(value);
      break;
    case 4:
      var value = new proto.TW.proto.BitcoinTransactionOutput;
      reader.readMessage(value,proto.TW.proto.BitcoinTransactionOutput.deserializeBinaryFromReader);
      msg.addOutputs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TW.proto.BitcoinTransaction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TW.proto.BitcoinTransaction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TW.proto.BitcoinTransaction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TW.proto.BitcoinTransaction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f !== 0) {
    writer.writeSint32(
      1,
      f
    );
  }
  f = message.getLocktime();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getInputsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.TW.proto.BitcoinTransactionInput.serializeBinaryToWriter
    );
  }
  f = message.getOutputsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.TW.proto.BitcoinTransactionOutput.serializeBinaryToWriter
    );
  }
};


/**
 * optional sint32 version = 1;
 * @return {number}
 */
proto.TW.proto.BitcoinTransaction.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.TW.proto.BitcoinTransaction.prototype.setVersion = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 lockTime = 2;
 * @return {number}
 */
proto.TW.proto.BitcoinTransaction.prototype.getLocktime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.TW.proto.BitcoinTransaction.prototype.setLocktime = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated BitcoinTransactionInput inputs = 3;
 * @return {!Array<!proto.TW.proto.BitcoinTransactionInput>}
 */
proto.TW.proto.BitcoinTransaction.prototype.getInputsList = function() {
  return /** @type{!Array<!proto.TW.proto.BitcoinTransactionInput>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.TW.proto.BitcoinTransactionInput, 3));
};


/** @param {!Array<!proto.TW.proto.BitcoinTransactionInput>} value */
proto.TW.proto.BitcoinTransaction.prototype.setInputsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.TW.proto.BitcoinTransactionInput=} opt_value
 * @param {number=} opt_index
 * @return {!proto.TW.proto.BitcoinTransactionInput}
 */
proto.TW.proto.BitcoinTransaction.prototype.addInputs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.TW.proto.BitcoinTransactionInput, opt_index);
};


proto.TW.proto.BitcoinTransaction.prototype.clearInputsList = function() {
  this.setInputsList([]);
};


/**
 * repeated BitcoinTransactionOutput outputs = 4;
 * @return {!Array<!proto.TW.proto.BitcoinTransactionOutput>}
 */
proto.TW.proto.BitcoinTransaction.prototype.getOutputsList = function() {
  return /** @type{!Array<!proto.TW.proto.BitcoinTransactionOutput>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.TW.proto.BitcoinTransactionOutput, 4));
};


/** @param {!Array<!proto.TW.proto.BitcoinTransactionOutput>} value */
proto.TW.proto.BitcoinTransaction.prototype.setOutputsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.TW.proto.BitcoinTransactionOutput=} opt_value
 * @param {number=} opt_index
 * @return {!proto.TW.proto.BitcoinTransactionOutput}
 */
proto.TW.proto.BitcoinTransaction.prototype.addOutputs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.TW.proto.BitcoinTransactionOutput, opt_index);
};


proto.TW.proto.BitcoinTransaction.prototype.clearOutputsList = function() {
  this.setOutputsList([]);
};


